//Do not edit this file. 
//This is auto-generated file, edit gp_error_codes instead.
#ifndef gp_error_codes_h
#define gp_error_codes_h

#define GP_EOK 0
#define GP_EARG 1
#define GP_EINDEX 2
#define GP_MYERROR 3
#define GP_NOMEM 4
#define GP_MEMVIOL 5
#define GP_ENULLPTR 6


#endif