//Do not edit this file. 
//This is auto-generated file, edit gp_error_codes instead.
#ifndef gp_error_codes_c
#define gp_error_codes_c

gpInt gp_errno;
gpString GP_ERRSTR[]={
(gpString)"No error",
(gpString)"Bad argument exception",
(gpString)"Index out of bound exception",
(gpString)"An example error",
(gpString)"Memory limit exceeded",
(gpString)"Memory Violation",
(gpString)"Null pointer not allowed",

};
#endif
