//Do not edit this filie. 
//This is autogenerated file, edit gp_error_codes istead
#define GP_EOK 0
#define GP_EARG 1
#define GP_EINDEX 2
#define GP_MYERROR 3
#define GP_NOMEM 4
#define GP_MEMVIOL 5
