//Do not edit this filie. 
//This is autogenerated file, edit gp_error_codes istead
#include "gp_types.h" 

gpInt gp_errno;
gpString GP_ERRSTR[]={
"No error",
"Bad argument excetion",
"Index out of boud exception",

};