/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpGestures_GP_Tap */

#ifndef _Included_gpGestures_GP_Tap
#define _Included_gpGestures_GP_Tap
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
