/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpGestures_GP_Move */

#ifndef _Included_gpGestures_GP_Move
#define _Included_gpGestures_GP_Move
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
