/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpGestures_GP_Press */

#ifndef _Included_gpGestures_GP_Press
#define _Included_gpGestures_GP_Press
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
