/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gp_Delegator */

#ifndef _Included_gp_Delegator
#define _Included_gp_Delegator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gp_Delegator
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gp_Delegator_test
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    recognize
 * Signature: (II[FI)Z
 */
JNIEXPORT jint JNICALL Java_gp_Delegator_recognize
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     gp_Delegator
 * Method:    isTap
 * Signature: ()Lgp/Tap;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isTap
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isPress
 * Signature: ()Lgp/Press;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isPress
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isFlick
 * Signature: ()Lgp/Flick;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isFlick
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isMove
 * Signature: ()Lgp/Move;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isMove
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isRotate
 * Signature: ()Lgp/Rotate;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isRotation
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isScroll
 * Signature: ()Lgp/Scroll;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isScroll
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isTwoFingerScroll
 * Signature: ()Lgp/TwoFingerScroll;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isTwoFingerScroll
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isTwoFingerScroll
 * Signature: ()Lgp/TwoFingerTap;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isTwoFingerTap
  (JNIEnv *, jobject);

/*
 * Class:     gp_Delegator
 * Method:    isZoom
 * Signature: ()Lgp/Zoom;
 */
JNIEXPORT jobject JNICALL Java_gp_Delegator_isZoom
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
